--1
UPDATE Worker
SET SALARY = CASE WHEN DEPARTMENT = 'Admin' THEN SALARY * 1.15 ELSE SALARY * 1.10 END;

--2
SELECT DISTINCT DEPARTMENT
FROM Worker;

--3
SELECT *
FROM Worker
WHERE FIRST_NAME LIKE '%b'
AND LEN(FIRST_NAME) >= 3;

--4
SELECT DEPARTMENT
FROM Worker
GROUP BY DEPARTMENT
HAVING COUNT(*) < 5;

--5
SELECT SALARY
FROM (
    SELECT SALARY, ROW_NUMBER() OVER (ORDER BY SALARY DESC) AS RowNum
    FROM Worker
) AS subquery
WHERE RowNum = 5;


--6
SELECT *
FROM (
    SELECT TOP 5 *
    FROM Worker
    ORDER BY WORKER_ID DESC
) AS subquery
ORDER BY WORKER_ID ASC;



--7
SELECT DEPARTMENT, MIN(SALARY)
FROM Worker
GROUP BY DEPARTMENT
HAVING MIN(SALARY) < AVG(SALARY);

--8
SELECT *
FROM Worker
WHERE DEPARTMENT = (
  SELECT DEPARTMENT
  FROM Worker
  WHERE FIRST_NAME = 'Foridul'
);

--9
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAME, *
FROM (
    SELECT TOP 5 *
    FROM Worker
    ORDER BY WORKER_ID
) AS subquery;


--10
SELECT *
FROM Worker
WHERE SALARY > (
  SELECT SALARY
  FROM Worker
  WHERE FIRST_NAME = 'Sanjoy'
);
